title: Yannick Meillier's Blog
description: Yannick Meillier's Blog

url: https://ymeillier.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 10

navigation:
 - title: Home
   url: /index.html
 - title: Articles (EN)
   url: /articles
 - title: Articles (中文)
   url: /articles-zh
 - title: Categories
   url: /categories
 - title: About
   url: /about
 - title: Donate
   url: /donate

social:
   github: ymeillier 
   #linkedin: 
   #facebook: profile.php?id=100014334455077
   email: xxx@xxx.xxx 

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      comments: false

google_analytics: ""

# development configurations
host: 0.0.0.0
